# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:Bi0DU79T3xeR6no9qAuDipecricF4qYsZM7tGZAr/yRfgNYn,iv:fPMT9gDeW5HJcFiLeH0y57sW0wQ4JQkK5TXTbxT0hX0=,tag:rIlgZd5DRlIIwZn3Y5kWDg==,type:str]
  credentials.json: ENC[AES256_GCM,data:LBYspvhMGAVtd+V0xSfxYueHTb/z+s3Pg8zeSfEEyKDhtoI4xSeONn+cWnOM31U3ibwmwwB+zrEuV8+hKjTg66P+nCwsjOxUm7BFhpaEmUiGgFrGDjaad0A/8gqTZHMFT870/WPtyCP/YbDIO8K7pnCRGZfrr75faSE3DFuHoNHEutcyQOyrByDxjTTstoyejCIAntLTKs9Q3hEhoJVIjjKjOV9njhTCBOq4l6bbsw==,iv:ugdZIWxxCC3xyc/6FFqujXjh6Ji1xDAXZBehrS0BaMQ=,tag:5mltLUt2GEtH5IfNpgEQwQ==,type:str]
sops:
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cmhTN2I2VlB5VStsaHZG
        NWRaMGJnMEY0ZkZuZmpkVlJxODg0MnEyZXlVCkhaWXlNbWFnd294aGd3UG8yN2FN
        M3huWWwwMjZuWktkZGpUM3crMlhXK3cKLS0tIEJWeStQUWdlKzVtSENDZi85ME5v
        Z2Q4NWZpSmZlQ2NxOThIM1lqbTNFRWcKt78pJ5jpI6R8mZPwmXW3UEsXamp3mR0B
        k3X38fSo84OmfW3wNdJ6x1bfqiQqJASQSSKkz9w3I/U0pZ2CFl3kCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-31T16:53:55Z"
  mac: ENC[AES256_GCM,data:pLnz06ffr3ZffPCVl7vhsZGLytm80QB3m7emohlOLws7ecWUcbQNtnnyOvOAHdAL/OV6ZDK/984z4PKOSnpw9Zrs4CohhOF+VVTMvBeDnuNBiwdARbHxPAAhMUIFQfXt1yvucUZYP+dBNK0cJVsQyEkeF5rmT4jZxA9lRTFLG08=,iv:UF6RJ68KQ8sxgMWhHrGQPcNrVi/T5NGFJ+kIf/X6xgU=,tag:+JVk2TQxvROUdGX/dPq3Vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.0
