# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:sSXqNMmw+qnJkrqMfqMPoZsMlMppTJ8JSCKFQLJhiWk=,iv:9mZ5YVn8OfOUGNywF/Q5TLanB/0XkALt+mkga6jAa+U=,tag:hjJbJ48heetUC+dTpHS/oA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNazhVSHZXTldPOUp6WHFQ
        RmM5R1UveW1mTys5VzlFZzV0V0VZSDA5UEVrCnZLa0tCRWVFUm9mRk91TXFEUUo4
        T1ovSnQ1bW96bXluZ0N6cEFGWm5DSjQKLS0tIDJyYTdTM2tsaHhQYmcwNFNIanVI
        Q0hmTHdHL2JkRVg2K0hQNDZFSDdHMHMKYEIGaQqjnrwIAgqLvANxF0XVGgKf/02C
        XgNshe82a3dLnDkj+6cet1hZI78EkUJwvcpqgwRM89duXiRDiboYmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T19:14:41Z"
  mac: ENC[AES256_GCM,data:1f3JlHls+BYN0Hne0MzSdVl4ZBw90rhDDgQoH/13mKJBnxh4Ddd2vCyNujdQXFDDqpFm0XukM6AnLBdRf4vKAE/oriGypwdSlMXGjfNh2wRamkU1a8QzDrQnCaZFjIXpXZyY1V/RVBFGPcCU66IWEvvcyoo6I8nbGsch02YUJUg=,iv:yHTunPw00ampMdUZzHp5APD3Q3DBo/SWDvSkdaoKuD4=,tag:7dhMELK0MULHWtRJbyHi+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
