# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:gIfOPhMRH1MvAasRap1BNs7urm0u7FltvQQ14tKrh6o=,iv:1Y8x9CUs0Jlks5tCgax6lcXmmxeXSjQZsARbcfRDsgY=,tag:2F70CjzXpaeleOOa2udXSg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c2VMZFU3M0pUbGtuQ3cw
        dVkvZXpGMTlPY3F5TWsyQUhvQUlJWmhHQ3hjCjRFVVNnaXZjRHZhdU5mR3A2Smdx
        ZW9LVzhMQU1zczczZUtRV0dGb2dSNU0KLS0tIGx3cEtJQlpPREJoekg4a3lvaUtq
        MnJDa2doaDJtMTYwdFVrc2NrUmNpK2sK+8jMdMhJ62Oo3ANlmZ30XETfyezw5aaS
        YrQkXToLFxQ15hb7jfZCwXsTZxHyqoMlI1Qg3P0ZNUihzsq/CIK6Bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T18:58:31Z"
  mac: ENC[AES256_GCM,data:gsbTgNjs63K0/DSlt7kr9FHdBauSTRDaQ3QBz9xDa7urAX/xemuxlRhsmV9BQeWwfsKqjBQ369ucnwsrTehvzluJSwYzrvrrj7xS27wyc/bTNSPDANRRh8bDR/ZcLtelZjdcvyqHnopZAzqMKmCummaAaMRDFUJmJ1l+7sf6zug=,iv:clW+QhZiYEwfnASxnWzFEz7TGu6m46QK7t1D6Y1QIsI=,tag:tih9EsHBTarU5azaW61D9g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
