# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:o5SxrdGRaeYui7rDbE5vO527szLU+kDryBDhAvsSSEI=,iv:2RqJg8MzZzWGDQ3oQTMD2mjFm1THitIHDxzotls/eA8=,tag:aROo02pAw4ECKiXp9ki7FQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMTlNL01qRG9ITDE0dXZJ
        UzNTYU0vYmhBYUZhV1IveVc1cEFBRThNRW1vClc5S01UOU1VSDUvRU41NklsN1Zr
        TXozS1orazJDdjROZjJuNEo0S0tDZkkKLS0tIG5GaG05WEU4VmhVR2QyeGhuK08z
        WjdwQkxpL1loSlNrWDl2c2pUK3k3TlkKx1yYgaHxkvr0wNiMTvsQ2E/Uqv/E2mJV
        RFMJd1z3oicRcdpdWaql5gn32ZEqK7fYdHGG0wWt8nlI1hdxYEjL1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-11T17:43:26Z"
  mac: ENC[AES256_GCM,data:w4GEc3GSGEQlTxcawqTSiCHxunPTS7U0UmHFOWTb8bYLhAG2IEZ1cNxPzAGtyD6GbGGJ4xp3+sttfGX2bA/fdnTudfMVEQXXdxcShmT98BZBQFBvPqHx2bgXDGJSYwOLzuOD6J13r6vZV3G+NCepKfYHMQIbtu6/jtI+o7Jd9zs=,iv:thvmDrw1a+8mLEgLyUuHc2LXL/HnQrIHNqexIvJtT5k=,tag:ZDwL0Al5SmONxmiCcL/nOg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
