# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:4tl1kgDDtwvmfI+3UJc=,iv:7duRwT74OQaXe8c9vHFC4GZ2aKq7Jooj4cJTRzav27I=,tag:CQEY4wGTtAt7ltv+6xXPpw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ogOkS2LBUU3chy5cloU2ehXrbGkhZAnjGg==,iv:uWSC6hZjrZIjxIpckt/1OXH96UHumJx3cD+BWAsPPTU=,tag:P+3oHCl+NLuYICbCTmEQuw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:eCQLcstl6xGmDhYM7UqFRvCT/n/6ciVX3KyGojyo4va+MBJs,iv:RSrEA/jNgSu2MMf5IKh6StCa60DvPmTG0vFvo8JM/8c=,tag:daN0MN2VaK7C7LMMLe/FEw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd0NVVzRwZmxBUm9PeUNs
        R1hNMTZodFhBSU1EdXcvdXFtOUpRUFF6MDBjCjdFZTU2aXR3UFBpajFhMHZmQjZ5
        Rk5RTEVHT1dSY2cxL0lLcWlCVDBFVUkKLS0tIFV2MHBydTYyMGo2dG55aE1YOWVo
        TFVmRXRueENsdFBoUDNPSVlDdzNsS3MKRaTjZfy79u/6DacSifTy403ZTLpHj7ol
        h7VbS6RAkFAdbcEcxuTlQfuCQFZuOzPgG6LEbBpp8FeZtK2fgtnLtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T19:11:07Z"
  mac: ENC[AES256_GCM,data:iZv3zLfGkXIW5MoVG3CKUZS/JS9RBNW4vWH+HPGxTVpULRfOa0NS0AHed+FUoj56z+iXQn//FNYyxRn5lyKNEuVXHc3uNC8LjG60oEFwfwOKWPTvFlHrBf3JrjTeTZEQ3HGMKxwdgq/P5/+Z1h4MIVEM4NPcrJnniEFKvJwYyrQ=,iv:+G3L/6EJUSLTEMU1vLi4Vt4uOehHSoai2SNvyKjM3dM=,tag:AIAL7t3wAVUmU4TZ8VaZcg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
