# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:BJ8uQ8zK4R5d9VSP4gM=,iv:ZNwl9V8M5nGvbCDpUEOXUjia9rCSqf6iL/SDb6g+dOQ=,tag:BMfcKIpO7dH1uK+BEc+u1g==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ECoslOPdcd5QxFZ2phmbh74QTNMINuzwwg==,iv:KfIuzFt1D+9r9lduLGq+DyP8NDZqeSOz5SvKPEa90HQ=,tag:RGkPB3BsECeYK/DQkuaPEA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:2Nbr/ZO4VQF9R0EL+Igkp8ZMcYxN2XPkg1FG3agVylYo0Kis,iv:oigOmm6Jnvmy4b0YYsDcPHCSTOi3+gv5CyLDnz5ZEEM=,tag:tKTd4+6WWyOKRAAMHiv5jg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMmM3ZnJaS3V1Z3hjU0dK
        dWxGU21kMlFBb0xBcGNIanE0QVJLa1Uybm40CkhXakRVMzBjQmcxT2o0R3FRY0Zo
        VVFPK3h5NHQzVHBEWUM2SUNiVlBoUlEKLS0tIElMbFlUczNzanBoaFdpSjRWMWZq
        d3p2ckhYMGNTSDBFTjJxZFRGdlRYZnMKG+4uG3Lg2TDlOs54tBEb/QcbwAMmHMzo
        AitaFNe4gp51v6f5wLfiYzYIcrjYo8eZXPF+pMu4HmK+Fn0Eb+ELXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-11T17:43:26Z"
  mac: ENC[AES256_GCM,data:ypvWyVab3moB71iqGafXkEEG60OjfDSPnUSHkiEyKslf/QUuEQ1cji5t4dlYgJcx10TPMiUsBbqDIyxIeD20yAUtnnjQEk8DXZj48BDAvwToOpj3s31UqKFnF6xy+eSmk94+tcBmipaqYVKBoW2vPvX5+iUoFyoQIhI28t6fHsA=,iv:a4+TQGISxRbJbk7tnvu2ZmuJUyCQZntKP5TpPQx8Dbo=,tag:sxoWPnPTQkgckCIcSVAytQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
