# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2ugyDIOBLEHoPXJYFIM=,iv:9S27gLeqrjMcLSbMyA1VmOMyZTXKHvpPTlSTU4pBoKk=,tag:Vm3mycfliZagFhXTw5ilAQ==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:uG9+s+ibIRQ4E6X+4HzI+7Ew3uTeltam4g==,iv:UY+FErI1Sxq9h2wlqq5Auec5zgIYB3boptUcCR3Y1kU=,tag:L2OEsg4VbaQFMATfibMLFA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tGuj8/JvqcI24w0WZmTnyF3K3AmhT5+2RCn5v4ONgplISN5z,iv:s+N7hfRMrpVtgv7ybAUzcVn9jtAOvmLyd0w1+8LxOHg=,tag:6pljrqblo8hnIVX49hyzXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxclYxYWowbUplT1ZnODhK
        ekw1V2ZyVVZ0R1dhZ0tFbnNWVFZtdmtoNHg4CkZNUm1HQzJMMHRXYmZXdEQ1OXRa
        NHJCbXBYZmdLUWtDd1huMEw5NUtHVncKLS0tIENmbVAyYklaVWFSa2FZS1NWdzJH
        dWlKd3UxbEJ1YmVHdFNyTTlaTTJ1RjAKUBAeJlR3MORotAKhvMnsp0QO3lpSDQ9U
        bmn+bLsDhuJmEgi37uNVS95Xf2Atu+pBJ90ZxtUwcohM45cniXX9BQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T19:14:41Z"
  mac: ENC[AES256_GCM,data:uYpSUH3MPYkbSRm8D13w7qS1ZhOIZAck/evbD4jBVdF6wO0pHzOvlEfFDAlkHehnCmemLTNEkqX/5vdmxogcw2bKSuFfJZitOakxV2NrtphacpNpvMcZqJJ9OnkXu4VY6ph1FLFPAYCTmaul4p3La0ZdDHXvXXO8dodRxkOzyDA=,iv:1N5cK9cUuByNHuFYn3O3mAyrXpf411l+GILfNWyq8DU=,tag:93ogqpczVP50jUFcTjor7g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
