# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:1u/ecbK01O1j0vt1wo3llFw9BrW5AwbztpT8kIelRANBUF1AqCtq8g==,iv:JPQo7SOBxv3GxJy89x6CinmOe/gVQ9rIGn+W2IArRvc=,tag:j7gLFtiCv03iuhpyiqrWMw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wh6jtumcme4v6sn27nsect5n0ysu0jrz4lu0qh0djhgf9euys4mqdtlply
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VnF5WEoxWmszaGR1ZkZv
        NkZtMDlZLzBmR1Y2RkEvNVE5aTlJTHJjSUE0CkhrRWs2VmR3VmIyVXM4NWVKSmpP
        UHFGUkkvM0EyMFRlQURjNWplc1lVUU0KLS0tIFJCU2FRUXY4ZDZrQzJHSVVIVFlv
        WFRRWFVRRjJIVzc4dW9ja0kxanpYV0kKnJdLt3n7H4YswHHcxg5zJ0wRaFIQ9oMx
        QSiRqtONHb37tfYJO2nndK/3bj0doRG5XqOPjX8x7nWuwr7GUYLRLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-31T17:25:40Z"
  mac: ENC[AES256_GCM,data:6dBZzRompQxHz7yZB7VJHHTuNJfMil6K7Z4TAOZURc7zONdwNW7MzHD4sXDwXWeTrMFwAfhPNu6jQjXk14n+yHBbFtd8iEoG60v3Mq3ejvdJKJ6pJBRBm7DwmLBPi4gP+gAMPXry3UX1pARBun4qZhXH8r6mmPx1CW5IzAC65Ck=,iv:sixEmbSi0zprO4ZwyoWJwD75dpGIu7tenI4o/p13ffA=,tag:XlHyRon1i75JhflTaOzVHg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
